[build]
  command = "npm run build"
  publish = "dist"

# Proxy till Railway-API:t
[[redirects]]
  from = "/api/*"
  to   = "https://chatify-api.up.railway.app/:splat"
  status = 200
  force  = true

# SPA-fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self'; img-src 'self' https://i.pravatar.cc data:; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; base-uri 'self'; frame-ancestors 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
